version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile
    ports:
      - "80:80"
    restart: always
    networks:
      - sqwid-network

  client:
    build:
      context: .
      dockerfile: client/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    networks:
      - sqwid-network

networks:
  sqwid-network:
    driver: bridge
